sync:
  defaults:
    ignore:
      paths:
        - ".idea/*"
        - ".idea/**"
        - "node_modules/*"
        - "node_modules/**"
        - "_DelSyncFiles/*"
        - "_DelSyncFiles/**"
        - "tmp/*"
        - "tmp/**"
        - "log/*"
        - "log/**"
        - "logs/*"
        - "logs/**"
        - "*.log"
        - ".DS_Store"
