tap "brona/iproute2mac"
tap "caskroom/cask"
tap "eugenmayer/dockersync"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "osx-cross/avr"
tap "sanemat/font"
brew "anyenv"
brew "autoconf"
brew "xz"
brew "awscli"
brew "freetype"
brew "gettext"
brew "libffi"
brew "glib"
brew "pixman"
brew "curl"
brew "zeromq"
brew "czmq"
brew "dfu-programmer"
brew "direnv"
brew "icu4c"
brew "harfbuzz"
brew "jpeg"
brew "libtool"
brew "pango"
brew "fontforge"
brew "fswatch"
brew "git"
brew "gobject-introspection"
brew "hadolint"
brew "imagemagick"
brew "imagemagick@6"
brew "iproute2mac"
brew "jpegoptim"
brew "jq"
brew "kompose"
brew "kubernetes-cli"
brew "libsodium"
brew "libyaml"
brew "mas"
brew "mecab"
brew "mecab-ipadic"
brew "mysql"
brew "peco"
brew "perl"
brew "postgresql"
brew "rsync"
brew "ruby"
brew "speedtest-cli"
brew "tree"
brew "unison"
brew "v8"
brew "vim"
brew "wget"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "eugenmayer/dockersync/unox"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "alfred"
cask "calibre"
cask "clipy"
cask "cyberduck"
cask "dbeaver-community"
cask "fork"
cask "franz"
cask "gimp"
cask "google-japanese-ime"
cask "graphiql"
cask "iina"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "mysqlworkbench"
cask "postman"
cask "rescuetime"
cask "sourcetree"
cask "tomighty"
cask "tor-browser"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "BetterSnapTool", id: 417375580
mas "Cinebench", id: 1438772273
mas "Disk Speed Test", id: 425264550
mas "Fantastical", id: 975937182
mas "Final Cut Pro", id: 424389933
mas "Just Focus", id: 1142151959
mas "LanScan", id: 472226235
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 715768417
mas "OmniFocus", id: 1346203938
mas "Quiver", id: 866773894
mas "Remotix", id: 466261145
mas "Screens", id: 1224268771
mas "Xcode", id: 497799835
